# OpenAI (ChatGPT) 配置
OPENAI_API_KEY = "sk-1pUmQlsIkgla3CuvKTgCrzDZ3r0pBxO608YJvIHCN18lvOrn"
OPENAI_API_BASE = "https://api.chatanywhere.tech/v1"

# DeepSeek 配置
DEEPSEEK_API_KEY = "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"
DEEPSEEK_API_BASE = "https://openrouter.ai/api/v1"

# Ollama 配置
OLLAMA_BASE_URL = "http://152.70.248.22:1234"
OLLAMA_DEEPSEEK_MODEL = "deepseek-r1:14b"