# OpenAI (ChatGPT) 配置
OPENAI_API_KEY = "sk-1pUmQlsIkgla3CuvKTgCrzDZ3r0pBxO608YJvIHCN18lvOrn"
OPENAI_API_BASE = "https://api.chatanywhere.tech/v1"

# DeepSeek 配置
DEEPSEEK_API_KEY = "sk-hiqxnuveyuckekjqbtdgbetspfjhxahdesakehbldzpuitzq"
DEEPSEEK_API_BASE = "https://api.siliconflow.cn/v1"

# Ollama 配置
OLLAMA_BASE_URL = "http://152.70.248.22:1234"
OLLAMA_DEEPSEEK_MODEL = "deepseek-r1:14b"